#!/bin/sh

cat > __obliv_swig.i << EOF
%include swig/scan/test_scanner.i
EOF

cp src/scan/test_scanner.cpp ./
cp libs/libtins.so ./

swig -c++ -ruby __obliv_swig.i

cat > extconf.rb << EOF
require "mkmf"

\$libs += "libtins.so"
\$warnflags += " -Wreturn-type -Wall -Wno-format"
create_makefile("test_scanner");
EOF

ruby extconf.rb
make

rm libtins.so
rm extconf.rb
rm test_scanner.cpp
rm test_scanner.o
rm __obliv_swig.i
rm __obliv_swig_wrap.o
rm __obliv_swig_wrap.cxx
rm Makefile

mv test_scanner.so _build/libs/
cp rmodules/scan/test_scanner.rb _build/rmodules/
cp rmodules/scan/ruby_scanner.rb _build/rmodules/
cp qml/test_scanner.qml _build/qml/
